// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transferencia.Api.Infrastructure;

#nullable disable

namespace Transferencia.Api.Migrations
{
    [DbContext(typeof(TransferenciaDbContext))]
    [Migration("20251003190328_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("Transferencia.Api.Domain.ChaveIdempotencia", b =>
                {
                    b.Property<string>("IdChaveIdempotencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Requisicao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resultado")
                        .HasColumnType("TEXT");

                    b.HasKey("IdChaveIdempotencia");

                    b.ToTable("ChavesIdempotencia");
                });

            modelBuilder.Entity("Transferencia.Api.Domain.Transferencia", b =>
                {
                    b.Property<string>("IdTransferencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdContaCorrente_Destino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdContaCorrente_Origem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("IdTransferencia");

                    b.ToTable("Transferencias");
                });
#pragma warning restore 612, 618
        }
    }
}
