// <auto-generated />
using System;
using ContaCorrente.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContaCorrente.Api.Migrations
{
    [DbContext(typeof(ContaCorrenteDbContext))]
    partial class ContaCorrenteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("ContaCorrente.Api.Domain.ChaveIdempotencia", b =>
                {
                    b.Property<string>("IdChaveIdempotencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Requisicao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resultado")
                        .HasColumnType("TEXT");

                    b.HasKey("IdChaveIdempotencia");

                    b.ToTable("ChavesIdempotencia");
                });

            modelBuilder.Entity("ContaCorrente.Api.Domain.ContaCorrente", b =>
                {
                    b.Property<string>("IdContaCorrente")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Salt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.HasKey("IdContaCorrente");

                    b.ToTable("ContasCorrentes");
                });

            modelBuilder.Entity("ContaCorrente.Api.Domain.Movimento", b =>
                {
                    b.Property<string>("IdMovimento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdContaCorrente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<char>("TipoMovimento")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("IdMovimento");

                    b.ToTable("Movimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
